In [4]:
from google.colab import files
uploaded = files.upload()

Saving heart_disease_dataset.csv to heart_disease_dataset.csv

In [5]:
!pip install scikit-learn seaborn joblib

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
    accuracy_score
)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [7]:
df = pd.read_csv("heart_disease_dataset.csv")
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholesterol,fasting_blood_sugar,resting_ecg,max_heart_rate,exercise_induced_angina,st_depression,st_slope,num_major_vessels,thalassemia,heart_disease
0,58,1,1,134,246,0,0,155,0,0.4,1,1,2,1
1,52,0,2,112,245,0,0,143,1,0.1,0,0,3,1
2,59,0,2,126,196,0,0,162,1,1.1,1,0,1,1
3,67,1,1,165,201,0,0,180,0,0.4,2,0,2,0
4,51,1,0,146,174,1,1,133,1,0.9,1,1,2,1

In [8]:
df.shape

(400, 14)

In [9]:
df["heart_disease"].value_counts()

heart_disease
1    222
0    178
Name: count, dtype: int64

In [10]:
df.isnull().sum()

age                        0
sex                        0
chest_pain_type            0
resting_blood_pressure     0
cholesterol                0
fasting_blood_sugar        0
resting_ecg                0
max_heart_rate             0
exercise_induced_angina    0
st_depression              0
st_slope                   0
num_major_vessels          0
thalassemia                0
heart_disease              0
dtype: int64

In [11]:
X = df.drop("heart_disease", axis=1)
y = df["heart_disease"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Size:", X_train.shape)
print("Testing Size:", X_test.shape)

Training Size: (320, 13)
Testing Size: (80, 13)

In [13]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
lr = LogisticRegression()
lr.fit(X_train_scaled, y_train)

lr_preds = lr.predict(X_test_scaled)
lr_probs = lr.predict_proba(X_test_scaled)[:,1]

print("Logistic Regression Results")
print(classification_report(y_test, lr_preds))
print("ROC-AUC:", roc_auc_score(y_test, lr_probs))
print("Accuracy:", accuracy_score(y_test, lr_preds))

Logistic Regression Results
              precision    recall  f1-score   support

           0       0.65      0.61      0.63        36
           1       0.70      0.73      0.71        44

    accuracy                           0.68        80
   macro avg       0.67      0.67      0.67        80
weighted avg       0.67      0.68      0.67        80

ROC-AUC: 0.7342171717171717
Accuracy: 0.675

In [15]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)

dt_preds = dt.predict(X_test)
dt_probs = dt.predict_proba(X_test)[:,1]

print("Decision Tree Results")
print(classification_report(y_test, dt_preds))
print("ROC-AUC:", roc_auc_score(y_test, dt_probs))
print("Accuracy:", accuracy_score(y_test, dt_preds))

Decision Tree Results
              precision    recall  f1-score   support

           0       0.53      0.44      0.48        36
           1       0.60      0.68      0.64        44

    accuracy                           0.57        80
   macro avg       0.57      0.56      0.56        80
weighted avg       0.57      0.57      0.57        80

ROC-AUC: 0.5631313131313131
Accuracy: 0.575

In [16]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

rf_preds = rf.predict(X_test)
rf_probs = rf.predict_proba(X_test)[:,1]

print("Random Forest Results")
print(classification_report(y_test, rf_preds))
print("ROC-AUC:", roc_auc_score(y_test, rf_probs))
print("Accuracy:", accuracy_score(y_test, rf_preds))

Random Forest Results
              precision    recall  f1-score   support

           0       0.65      0.56      0.60        36
           1       0.67      0.75      0.71        44

    accuracy                           0.66        80
   macro avg       0.66      0.65      0.65        80
weighted avg       0.66      0.66      0.66        80

ROC-AUC: 0.76010101010101
Accuracy: 0.6625

In [17]:
svm = SVC(probability=True)
svm.fit(X_train_scaled, y_train)

svm_preds = svm.predict(X_test_scaled)
svm_probs = svm.predict_proba(X_test_scaled)[:,1]

print("SVM Results")
print(classification_report(y_test, svm_preds))
print("ROC-AUC:", roc_auc_score(y_test, svm_probs))
print("Accuracy:", accuracy_score(y_test, svm_preds))

SVM Results
              precision    recall  f1-score   support

           0       0.62      0.58      0.60        36
           1       0.67      0.70      0.69        44

    accuracy                           0.65        80
   macro avg       0.65      0.64      0.64        80
weighted avg       0.65      0.65      0.65        80

ROC-AUC: 0.735479797979798
Accuracy: 0.65

In [18]:
models = {
    "Logistic Regression": roc_auc_score(y_test, lr_probs),
    "Decision Tree": roc_auc_score(y_test, dt_probs),
    "Random Forest": roc_auc_score(y_test, rf_probs),
    "SVM": roc_auc_score(y_test, svm_probs)
}

models

{'Logistic Regression': np.float64(0.7342171717171717),
 'Decision Tree': np.float64(0.5631313131313131),
 'Random Forest': np.float64(0.76010101010101),
 'SVM': np.float64(0.735479797979798)}

In [19]:
joblib.dump(rf, "heart_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [20]:
joblib.dump(lr, "heart_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [21]:
files.download("heart_model.pkl")
files.download("scaler.pkl")

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score

print("Accuracy:", accuracy_score(y_test, rf_preds))
print("\nClassification Report:\n")
print(classification_report(y_test, rf_preds))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, rf_preds))
print("\nROC-AUC Score:", roc_auc_score(y_test, rf_probs))

Accuracy: 0.6625

Classification Report:

              precision    recall  f1-score   support

           0       0.65      0.56      0.60        36
           1       0.67      0.75      0.71        44

    accuracy                           0.66        80
   macro avg       0.66      0.65      0.65        80
weighted avg       0.66      0.66      0.66        80


Confusion Matrix:

[[20 16]
 [11 33]]

ROC-AUC Score: 0.76010101010101

In [23]:
from sklearn.ensemble import RandomForestClassifier

rf_improved = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    class_weight="balanced",
    random_state=42
)

rf_improved.fit(X_train, y_train)

rf_preds = rf_improved.predict(X_test)
rf_probs = rf_improved.predict_proba(X_test)[:,1]

from sklearn.metrics import classification_report, roc_auc_score, accuracy_score

print("Accuracy:", accuracy_score(y_test, rf_preds))
print("\nClassification Report:\n")
print(classification_report(y_test, rf_preds))
print("\nROC-AUC:", roc_auc_score(y_test, rf_probs))

Accuracy: 0.675

Classification Report:

              precision    recall  f1-score   support

           0       0.67      0.56      0.61        36
           1       0.68      0.77      0.72        44

    accuracy                           0.68        80
   macro avg       0.67      0.66      0.66        80
weighted avg       0.67      0.68      0.67        80


ROC-AUC: 0.7765151515151516

In [24]:
from sklearn.linear_model import LogisticRegression

lr_tuned = LogisticRegression(
    C=0.5,
    class_weight="balanced",
    max_iter=1000
)

lr_tuned.fit(X_train_scaled, y_train)

lr_preds = lr_tuned.predict(X_test_scaled)
lr_probs = lr_tuned.predict_proba(X_test_scaled)[:,1]

from sklearn.metrics import classification_report, roc_auc_score, accuracy_score

print("Accuracy:", accuracy_score(y_test, lr_preds))
print("\nClassification Report:\n")
print(classification_report(y_test, lr_preds))
print("\nROC-AUC:", roc_auc_score(y_test, lr_probs))

Accuracy: 0.675

Classification Report:

              precision    recall  f1-score   support

           0       0.62      0.72      0.67        36
           1       0.74      0.64      0.68        44

    accuracy                           0.68        80
   macro avg       0.68      0.68      0.67        80
weighted avg       0.68      0.68      0.68        80


ROC-AUC: 0.7348484848484849

In [25]:
import joblib

joblib.dump(rf_improved, "heart_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [28]:
from google.colab import files
files.download("heart_model.pkl")
files.download("scaler.pkl")